### ISSUE TITLE
[Feature Request] Multiple Notifiers

### ISSUE THREAD

**Issue by saschabrockel** [RafhaanShah/Container-Mon#3]
Is it possible to have multiple notifiers like Telegram and Discord together? If yes, how?

**Comment by RafhaanShah** [comment]
Hi!

The way the app is currently set up it does not support multiple notifiers, as it uses a single config environment variable `CONTAINERMON_NOTIFICATION_URL`.

Definitely an improvement I can look into in the future though.

If you are comfortable modifying the source code you can definitely do this for yourself, have a look at [line 206 of `app.go`](https://github.com/RafhaanShah/Container-Mon/blob/master/app.go#L206) to see how the notification works, and you can hard-code multiple notification URLs there for your use.

**Comment by RafhaanShah** [comment]
Feature available in `v1.0.2`, use `|` to separate different URLs, e.g `CONTAINERMON_NOTIFICATION_URL=telegeram|slack`
