### ISSUE TITLE
[Feature Request] Custom Message Prefix

### ISSUE THREAD

**Issue by seansheep** [RafhaanShah/Container-Mon#4]
Is it possible to add a custom message prefix or other custom content to alerts?

For example, If I'm monitoring more than one server from multiple instances of container-mon, I'd like to add a prefix to the (telegram) message to let me know which instance is sending me the container alert (i.e. the server name).

Something like an environment variable CONTAINERMON_MESSAGE_PREFIX which gets appended to the beginning of the alert message?

**Comment by RafhaanShah** [comment]
Will add it to the list of features for the next release when I have some time to work on it 👍

**Comment by RafhaanShah** [comment]
Feature available in `v1.0.2`, use `CONTAINERMON_MESSAGE_PREFIX` 😃

**Comment by seansheep** [comment]
Much appreciated 👍

**Comment by seansheep** [comment]
I notice that if you add a space to the end of the new environment variable it gets trimmed off.
eg if environment variable is set as

- "CONTAINERMON_MESSAGE_PREFIX=server1: " 

(with a space at the end) then the resulting message will be

"server1:Container /xyz is not healthy"

(without a space between the prefix and main message)

It would be good to either:

- not trim the space if there is one at the end of the prefix (or)
- automatically add a space between the prefix and the main message if a prefix variable exists

**Comment by RafhaanShah** [comment]
My bad 😂 will fix

**Comment by RafhaanShah** [comment]
`CONTAINERMON_MESSAGE_PREFIX` should not be trimmed on `v1.0.4` 🙂
