### ISSUE TITLE
[Question] How to validate notifications with shoutrrr CLI?

### ISSUE THREAD

**Issue by jpbaril** [RafhaanShah/Container-Mon#40]
Docs say to validate notification URLs and gives that link: https://containrrr.dev/shoutrrr/v0.8/getting-started/#through_the_cli

This link shows how to use the shoutrrr cli but I cannot find that binary in the container.
So how are we supposed to validate our URLs ?

Thank you

**Comment by RafhaanShah** [comment]
You will need to install the CLI following the instructions (on any machine / container), the container doesn't come with it :)
